package h.r.m;

import java.awt.Dimension;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.*;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Hrmmenu extends javax.swing.JFrame {
    
    public Hrmmenu() {
        initComponents();//Initializes all java swing components *using Netbeans IDE
        this.setSize(1042, 768);//frame size is defined
        this.setTitle("HUMAN RESOURCE MANAGEMENT");//frame title is defined
        Dimension sd = Toolkit.getDefaultToolkit().getScreenSize();//Dimension-sets the location of container manually//Toolkit-methods in this class joins platform independent classes in awt
        setLocation(sd.width / 2 - this.getWidth() / 2, sd.height / 2 - this.getHeight() / 2);//sets the location of container manually
        
    }

     /*
	 This method is called from within the constructor to initialize the form.
     Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		jMenu4 = new javax.swing.JMenu();
		m13=new javax.swing.JMenuItem();
        m5 = new javax.swing.JMenuItem();
        m6 = new javax.swing.JMenuItem();
        m7 = new javax.swing.JMenuItem();
        m8 = new javax.swing.JMenuItem();
        m10 = new javax.swing.JMenuItem();
        m11 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        m9 = new javax.swing.JMenuItem();
		m12 = new javax.swing.JMenuItem();
		m14 = new javax.swing.JMenuItem();
		//all variables are initialized

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));//Label background color is set
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s.gif")));//Image is set inside jLabel1 which has same size as of framesize
        jLabel1.setText("jLabel1");//label text is set
        getContentPane().add(jLabel1);//obtains reference of content pane where content pane is simple intermediate container which is inherited by JFrame
        jLabel1.setBounds(0, 0, 1042, 768);//label size defined

        jMenu1.setForeground(new java.awt.Color(58, 89, 153));//menu color is set
        jMenu1.setText("Manage");//menu text is defined or set
        jMenu1.setFont(new java.awt.Font("Arial", 1, 18));//Font name ,size and type defined 
		
	jMenu2.setForeground(new java.awt.Color(58, 89, 153));//menu color is set
        jMenu2.setText("Register");//menu text is defined or set
        jMenu2.setFont(new java.awt.Font("Arial", 1, 18));//Font name ,size and type defined 
		
	jMenu3.setForeground(new java.awt.Color(58, 89, 153));//menu color is set
        jMenu3.setText("Add Notice");//menu text is defined or set
        jMenu3.setFont(new java.awt.Font("Arial", 1, 18));//Font name ,size and type defined

		jMenu4.setForeground(new java.awt.Color(58, 89, 153));//menu color is set
        jMenu4.setText("Help");//menu text is defined or set
        jMenu4.setFont(new java.awt.Font("Arial", 1, 18));//Font name ,size and type defined 
		
        m5.setBackground(new java.awt.Color(255, 255, 255));
        m5.setFont(new java.awt.Font("Times New Roman", 1, 18));
        m5.setForeground(new java.awt.Color(58, 89, 153));
        m5.setText("Staff Registration");
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });
        jMenu2.add(m5);

        m6.setBackground(new java.awt.Color(255, 255, 255));
        m6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        m6.setForeground(new java.awt.Color(58, 89, 153));
        m6.setText("Student Registration");
        m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6ActionPerformed(evt);
            }
        });
        jMenu2.add(m6);

        m7.setBackground(new java.awt.Color(255, 255, 255));
        m7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        m7.setForeground(new java.awt.Color(58, 89, 153));
        m7.setText("Weekly schedule");
        m7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m7ActionPerformed(evt);
            }
        });
        jMenu1.add(m7);
		
		m10.setBackground(new java.awt.Color(255, 255, 255));
        m10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        m10.setForeground(new java.awt.Color(58, 89, 153));
        m10.setText("Notice for Staff");
        m10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m10ActionPerformed(evt);
            }
        });
        jMenu3.add(m10);

        m8.setBackground(new java.awt.Color(255, 255, 255));
        m8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        m8.setForeground(new java.awt.Color(58, 89, 153));
        m8.setText("Notice for Students");
        m8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m8ActionPerformed(evt);
            }
        });
        jMenu3.add(m8);

        

        m11.setBackground(new java.awt.Color(255, 255, 255));
        m11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        m11.setForeground(new java.awt.Color(58, 89, 153));
        m11.setText("News & Notifications");
        m11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m11ActionPerformed(evt);
            }
        });
		
		jMenu1.add(m12);

		m13.setBackground(new java.awt.Color(255, 255, 255));
        m13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        m13.setForeground(new java.awt.Color(58, 89, 153));
        m13.setText("User Guide");
        m13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m13ActionPerformed(evt);
            }
        });
		jMenu4.add(m13);
		
		m14.setBackground(new java.awt.Color(255, 255, 255));
        m14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        m14.setForeground(new java.awt.Color(58, 89, 153));
        m14.setText("Feedback");
        m14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m14ActionPerformed(evt);
            }
        });
		jMenu1.add(m14);
		
        m12.setBackground(new java.awt.Color(255, 255, 255));
        m12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        m12.setForeground(new java.awt.Color(58, 89, 153));
        m12.setText("Leave Management");
        m12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m12ActionPerformed(evt);
            }
        });
		
        jMenu1.add(m11);

        

        jMenu5.setForeground(new java.awt.Color(58, 89, 153));
        jMenu5.setText("Logout");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        m9.setBackground(new java.awt.Color(255, 255, 255));
        m9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        m9.setForeground(new java.awt.Color(58, 89, 153));
        m9.setText("Confirm");
        m9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m9ActionPerformed(evt);
            }
        });
        jMenu5.add(m9);

		jMenuBar1.add(jMenu2);
		jMenuBar1.add(jMenu3);
		jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu5);
		jMenuBar1.add(jMenu4);
		

        setJMenuBar(jMenuBar1);

        pack();//sets the frame size as per need
    }

    private void m9ActionPerformed(java.awt.event.ActionEvent evt) {
        Hrmlogin h=new Hrmlogin();//after ending from menu, control will go to login menu
        h.setVisible(true);
		//System.exit(0);//if not want to do like this perform System.exit(0) instead this h object of Hrmlogin
    }

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {
        Hrmteachers ht = new Hrmteachers();//teacher registration frame will open after menu item m5 will be clicked
        ht.setVisible(true);
    }

    private void m6ActionPerformed(java.awt.event.ActionEvent evt) {
        Hrmstudents students = new Hrmstudents();//students registration frame will open after menu item m6 will be clicked
        students.setVisible(true);
    }

    private void m7ActionPerformed(java.awt.event.ActionEvent evt) {
        Hrmscheduler sch = new Hrmscheduler();//Scheduler frame will open after menu item m7 will be clicked
        sch.setVisible(true);
    }

    private void m11ActionPerformed(java.awt.event.ActionEvent evt) {
        Hrmnotify notify = new Hrmnotify();//Notification frame will open after menu item m11 will be clicked
        notify.setVisible(true);
    }

    private void m10ActionPerformed(java.awt.event.ActionEvent evt) {
        Hrmtnotice tt = new Hrmtnotice();//Teacher notice frame will open after menu item m11 will be clicked
        tt.setVisible(true);
    }

    private void m8ActionPerformed(java.awt.event.ActionEvent evt) {
        Hrmsnotice st = new Hrmsnotice();//Student notice frame will open after menu item m11 will be clicked
        st.setVisible(true);
    }
	
	private void m12ActionPerformed(java.awt.event.ActionEvent evt) {
        Hrmleave le = new Hrmleave();//Leave management frame will open after menu item m11 will be clicked
        le.setVisible(true);
    }
	
	private void m14ActionPerformed(java.awt.event.ActionEvent evt) {
        Hrmfeedback fe = new Hrmfeedback();//Feedback frame will open after menu item m11 will be clicked
        fe.setVisible(true);
    }
	private void m13ActionPerformed(java.awt.event.ActionEvent evt) {
        if(evt.getSource()==m13)
		{String str="src/H.txt";
		File f=new File(str);
		Desktop d=Desktop.getDesktop();	
		try{
			d.open(f);
		}catch(Exception e)
		{}
		
    }
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Hrmmenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify without concerning developers
    private javax.swing.JLabel jLabel1;//used for background image icon purpose
    private javax.swing.JMenu jMenu1;//menu for Management
    private javax.swing.JMenu jMenu2;//menu for Registration
    private javax.swing.JMenu jMenu3;//menu for Notice
	private javax.swing.JMenu jMenu4;//menu for Help
    private javax.swing.JMenu jMenu5;//menu for logout
    private javax.swing.JMenuBar jMenuBar1;//menubar
    private javax.swing.JMenuItem m10;//menu item with text notice for staff
    private javax.swing.JMenuItem m11;//menu item with text news and notifications
    private javax.swing.JMenuItem m5;//menu item with text teacher registration
    private javax.swing.JMenuItem m6;//menu item with text student registration
    private javax.swing.JMenuItem m7;//menu item with text weekly schedule
    private javax.swing.JMenuItem m8;//menu item with text Notice for student
    private javax.swing.JMenuItem m9;//menu item with text Confirm
    private javax.swing.JMenuItem m12;//menu item with text Leave management
	private javax.swing.JMenuItem m13;//menu item with text User Guide
	private javax.swing.JMenuItem m14;//menu item with text Feedback
    // End of variables declaration                   
}