
package h.r.m;

import static java.awt.Color.GREEN;
import java.awt.Dimension;
import java.awt.Toolkit;


public class Hrmwelcome extends javax.swing.JFrame {

    
    public Hrmwelcome() {
        initComponents();
        this.setSize(1042, 768);//frame size is defined
        this.setTitle("HUMAN RESOURCE MANAGEMENT");//frame title is defined
        Dimension sd = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(sd.width / 2 - this.getWidth() / 2, sd.height / 2 - this.getHeight() / 2);//sets the location of container manually
        progress ps = new progress();//progessbar variable
        ps.start();//progessbar thread will start excuting
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
 //   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        pb = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
		//all variables are initialized

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 3, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME TO HUMAN RESOURCE MANAGEMENT SYSTEM");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(0, 20, 990, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Project Developed By :-");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(10, 80, 320, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1. Sahil Shaikh");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(10, 140, 230, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2. Prathamesh Ranshur");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(10, 200, 230, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3. Adesh Ramgude");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(10, 260, 230, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("4. Akash Rokade");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(10, 320, 230, 40);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(20, 20, 990, 580);

        jLayeredPane2.setBackground(new java.awt.Color(255, 0, 0));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pb.setForeground(new java.awt.Color(10, 250, 15));
        pb.setBorder(new javax.swing.border.MatteBorder(null));
        jLayeredPane2.add(pb);
        pb.setBounds(20, 10, 950, 16);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(20, 640, 990, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download-2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 1042, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Hrmwelcome().setVisible(true);
            }
        });
    }

     class progress extends Thread { //This block will be responsible for excution of progessbar

        int i = 0;


        public void run() {
            for (int j = 0; j <= 10; j++) {
                System.out.println("" + i);
                if (i < 100) {
                    i = i + 20;
                    pb.setValue(i);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                       System.out.println("Contact the developers of this project");
                    }
                } else {
                    Hrmlogin authenticate = new Hrmlogin();
                    authenticate.setVisible(true);
                    setVisible(false);
                }
            }
        }
    }

     
    // Variables declaration - do not modify without concerning developers
    private javax.swing.JLabel jLabel1;//used for background image icon purpose
    private javax.swing.JLabel jLabel2;//Title is defined in this variable
    private javax.swing.JLabel jLabel3;//Name of all developers
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;//all 4 group members name defined
    private javax.swing.JLayeredPane jLayeredPane1;//used for all text
    private javax.swing.JLayeredPane jLayeredPane2;//used for progessbar
    private javax.swing.JProgressBar pb;//progessbar variable
    // End of variables declaration
}